### ISSUE TITLE
[Feature request] deserialization from different naming case (snake_case to camelCase)

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [GillianPerard/typescript-json-serializer#91] opened 2020-07-30 01:23 UTC

**Comment by pratamatama** [comment] 2020-11-03 20:12
Hi @GillianPerard , sorry to bother by mentioning on a closed thread but I don't want to create a duplicate regardless the same requirement of our app. As you asks for an example to be provided, I have some that I think related and will be useful.

As @AlaaEldeenYsr posted, we have the case where it require us to use a specific naming conventions to make features provided by the backend framework to work as expected. Let's say in this case; Laravel, which the database column naming conventions are set to `snake_case` by default to make all the relationships works without having to explicitly define each FK of the relationships.

It did happen in our case where we need a serialization package to support us/our team and save some time instead of serializing and deserializing it manually which leads me to this package. But the problem is, our backend were already using `snake_case` conventions and mapping the response would take much time. It would be very convenient if there is an option on the `serialize` and `deserialize` method by defining it's naming convention, for example:

```typescript
@Serializable()
class Post {
  constructor (
    id: number,
    post_category_id: number,
    title: string,
    createdAt: Date,
    updatedAt: Date,
  ) {
    super(id, postCategoryId, title, createdAt, updatedAt);
  }
}

const json = {
  id: 1,
  post_category_id: 1,
  title: "foo",
  created_at:  "2020-11-02T07:47:12.000+07:00",
  updated_at:  "2020-11-02T07:47:12.000+07:00",
}

const deserialized = deserialize<Post>(json, Post, Format.snake)
console.log(deserialized)

/*
result: Post {
  id: 1,
  postCategoryId: 1,
  name: "foo",
  createdAt: "2020-11-02T07:47:12.000+07:00",
  updatedAt: "2020-11-02T07:47:12.000+07:00"
}
*/

const serialized = serialize(deserialized, Format.snake)
console.log(serialized)

/*
result: {
  id: 1,
  post_category_id: 1,
  name: "foo",
  created_at: "2020-11-02T07:47:12.000+07:00",
  updated_at: "2020-11-02T07:47:12.000+07:00"
}
*/
```

And maybe, instead of making an enum and passing it on the method directly, we could just use a config file to define the how the package should behave but that's for another story. For now, I'll just tell my team to map it from the server side.

Anyway, I found this package very useful and I would like to say many thanks for making it. I also have a [reference](https://pub.dev/packages/json_serializable) that maybe will be useful for you and the teams to add new features on the package for the next releases. I don't meant to be rude by comparing your package to that one I referenced so please don't take it personally. It doesn't work either for Typescript 😛

Thank you very much for having time on reading it. Have good day!

Best Regards,
Tamma

**Comment by GillianPerard** [comment] 2020-11-04 07:35
Hi! Thank you to post it here, perhaps we will be able to fix your problem 😊.

Just two things before doing anything ahah:

- I must tell you that if you use, for your front-end: 
  - React does not support `Decorator` when I tested it
  - Angular removes decorators from constructor params, so you are able to only decorate class properties
  - For others I don't know, this lib works mainly for NodeJS or NodeTS I should say 😛
- Even if the only constraint you have is to format from `snake case` to `kebab-case` you must decorate all the properties you want to serialize/deserialize with `@JsonProperty()` because Typescript has no introspection so if I inspect a class I can not see any properties.

Imagine that I provide a new feature as you proposed:

```ts
// Your example
const deserialized = deserialize<Post>(json, Post, Format.snake)
const serialized = serialize(deserialized, Format.snake)

// Mine
const toKebabCase = () => {...};
const toSnakeCase = () => {...};
const deserialized = deserialize<Post>(json, Post, {formatName: toKebabCase});
const serialized = serialize(deserialized, {formatName: toSnakeCase});
```

With this solution I let people define their own methods to format the property names; what are your mind about that? 😊

Best regards,
Gillian Pérard

**Comment by pratamatama** [comment] 2020-11-05 22:04
Hi @GillianPerard ! It would work and a very good idea regarding to the limitation by some frameworks, but I think it will be a little bit repetitive since we must first write our own formatting method. But well, not a big deal..

And to be honest, we don't know much about React and Angular as well as the side effect from the given proposal since we use Vue3 for our front-end and as for the decorators, it just works as is when we use it.

```typescript
import { JsonProperty, Serializable } from 'typescript-json-serializer'

@Serializable()
export class Gender {
  @JsonProperty() id!: number
  @JsonProperty() name!: string
  @JsonProperty() createdAt!: Date
  @JsonProperty() updatedAt!: Date
}
```

I was wondering something simpler like maybe this:

```typescript
import { JsonProperty, Serializable, Format } from 'typescript-json-serializer'

@Serializable({
  serialize: Format.snake,
  deserialize: Format.snake,
})
export class Gender {
  @JsonProperty() id!: number
  @JsonProperty() name!: string
  @JsonProperty() createdAt!: Date
  @JsonProperty() updatedAt!: Date
}
```

So we don't need to explicitly defines it on the `serialize` and `deserialize` method. Is it possible? How do you think?

Anyways, back to your example, if it works and not a breaking change, then why not? It still very useful.
I agree with it. (●'◡'●)

Best regards,
Tamma

**Comment by GillianPerard** [comment] 2020-11-09 16:28
Hi, I started to develop the new feature but I've another question:

If you have nested class, this class should "inherit" from the `Serializable` format option or not?

Example:
```ts
const modifyPropertyNames = () =>  {...}

@Serializable()
export class Address {
  @JsonProperty() id!: number
  @JsonProperty() city!: string
  @JsonProperty() cityCode!: string
}

@Serializable({formatPropertyNames: modifyPropertyNames})
export class User {
  @JsonProperty() id!: number
  @JsonProperty() name!: string
  @JsonProperty() address: Address
  @JsonProperty() createdAt!: Date
  @JsonProperty() updatedAt!: Date
}
```

**Comment by pratamatama** [comment] 2020-11-10 03:56
Hi, it could be an option i think, what if making a conditional property for it? I think it will be more flexible for us to decide whether or not the model should inherit.

maybe like this?
```typescript
const toCamelCase = () =>  {...}

@Serializable()
export class Address {
  @JsonProperty() city!: string
  @JsonProperty() cityCode!: string
}

@Serializable({ formatPropertyNames: toCamelCase, inherit: true | false(default)  })
export class User {
  @JsonProperty() id!: number
  @JsonProperty() name!: string
  @JsonProperty() address: Address
  @JsonProperty() createdAt!: Date
  @JsonProperty() updatedAt!: Date
}
```

**Comment by GillianPerard** [comment] 2020-11-10 07:03
I agree with both solutions but for the moment I'll implement the second one.

This feature is not really easy to handle ^^.

**Comment by GillianPerard** [comment] 2020-11-10 15:53
I've a big problem, I thought (stupidly) that the class decorator was called before property decorator and finally no...
So I can't replace the name of the `JsonProperty` when the the property decorator is running because the `Serializable` has not been called yet and so I can't retrieve the format function from `options`.

The only way I see is:
```ts
@Serializable({formatPropertyNames: {
  onSerialize: toSnakeCase,
  onDeserialize: toCamelCase
}})
export class User {
  @JsonProperty() id!: number
  @JsonProperty() name!: string
  @JsonProperty() address: Address
  @JsonProperty() createdAt!: Date
  @JsonProperty() updatedAt!: Date
}
```

What do you think, is that ok for you ?

**Comment by pratamatama** [comment] 2020-11-11 05:07
Oh.. What an unfortunate.. But well, yeah, that's totally fine.. I see no problem with that.. :)

**Comment by GillianPerard** [comment] 2020-11-11 07:25
Finally, I push the new feature on 2.5.0 😊

And found a way to do it like this:
```ts
@Serializable({formatPropertyNames: toSnakeCase})
export class User {
  @JsonProperty() id!: number
  @JsonProperty() name!: string
  @JsonProperty() address: Address
  @JsonProperty() createdAt!: Date
  @JsonProperty() updatedAt!: Date
}
```

**Comment by pratamatama** [comment] 2020-11-11 07:37
Woaahh cool.... Aight.. updating now haha.. Thanks for the update! 🎉

**Comment by GillianPerard** [comment] 2020-11-11 07:38
Tell me if it good then I close the issue!

**Comment by pratamatama** [comment] 2020-11-11 09:00
Hi there! I've just tested the update, works really good. 👍
You saved us a week from mapping resources manually. Huge thanks for this. 😂

```typescript
import { toSnakeCase } from '@/utils/Formatter'

@Serializable({ formatPropertyNames: toSnakeCase })
export class PersonalInfo {
  @JsonProperty() id!: number
  @JsonProperty() genderId!: number
  @JsonProperty() bloodTypeId!: number
  @JsonProperty() religionId!: number
  ...
  ...
}
```

from GET + PATCH request:
![image](https://user-images.githubusercontent.com/42239243/98790358-2b67f800-2436-11eb-80a7-ef8906ab0bdd.png)

**Comment by GillianPerard** [comment] 2020-11-11 09:07
I'm really happy for your team that my lib could help you!

Thank you too, to use it and reports bug/enhancement 😊

**Closed** 2020-11-11 09:07 UTC
Labels: enhancement

**Comment by MilanObrenovic** [comment] 2022-12-17 16:49
> 

where did toSnakeCase come from? What's the package name?

**Comment by GillianPerard** [comment] 2022-12-17 18:25
You can provide your own function or use one from an npm package.

This lib does not provide formater.
